### ISSUE TITLE
RescriptReactErrorBoundary not working in v0.11

### ISSUE THREAD

**Issue by vasco3** [rescript-lang/rescript-react#87] opened 2023-02-02 22:22 UTC
I described it in the [forum](https://forum.rescript-lang.org/t/how-to-use-react-error-boundaries/3682/6)
but here it goes as well

prior to the upgrade to v0.11 I was using this
```res
<RescriptReactErrorBoundary
    fallback={_err => <div> {"An error occurred"->React.string} </div>}>
     <Viewer />    
</RescriptReactErrorBoundary>
```

The compiler is now throwing this error
```
This has type:
(
  ~children: React.element,
  ~fallback: RescriptReactErrorBoundary.params<'a> => React.element,
) => React.element
Somewhere wanted: React.component<'b> (defined as 'b => Jsx.element)
```

any idea why it is now not working?

**Comment by cknitt** [comment] 2023-05-02 09:39
I tried

```rescript
<RescriptReactErrorBoundary fallback={_err => <div> {"An error occurred"->React.string} </div>}>
  <SomeTestComponent />
</RescriptReactErrorBoundary>
```

(with the latest ReScript 11 + @rescript/react alpha) and cannot reproduce any compiler errors.

Closing this issue for now. If you have a test project for reproducing the problem, we can reopen and investigate.

**Closed by cknitt** 2023-05-02 09:39 UTC
